const productData = [
    {
      id: 3,
      name: 'Puma Shoes Summer 2023',
      description: [
        'All types of sports use',
        'Product is made of real leather',
        'High build quality',
        'Long-lasting color',
        '30 days moneyback guarantee',
      ],
      category: 'Category A',
      categoryGrid: ['Fashion', 'Sports'],
      color: 'Red',
      colorGrid: { Blue: { id: 1, imgLink: require('./assets/roboarm.jpg') }, Red: { id: 2, imgLink: require('./assets/roboarm.jpg') } },
      sizeGrid: { L: 1, M: 1, XL: 5 },
      return: 30,
      totalSold: 25,
      rating: 4.5,
      totalRatings: 100,
      discount: 20,
      saleDiscount: 30,
      previousPrice: 50,
      currentPrice: 40,
      condition: 'New With Box',
      image: require('./assets/logo.png'),
      link: 'product1-link',

    },
    {
      id: 3,
      name: 'x',
      description: ['description1', 'description2', 'description3'],
      category: 'Electronics',
      color: { Blue: { id: 1, imgLink: require('./assets/roboarm.jpg') }, Red: { id: 2, imgLink: require('./assets/roboarm.jpg') } },
      size: { L: 1, M: 1, XL: 5 },
      return: 30,
      totalSold: 25,
      rating: 4.5,
      totalRatings: 100,
      discount: 20,
      saleDiscount: 30,
      previousPrice: 50,
      currentPrice: 40,
      condition: 'New With Box',
    },
    {
      id: 1,
      name: 'Puma Shoes Summer 2022',
      description: [
        'All types of sports use',
        'Product is made of real leather',
        'High build quality',
        'Long-lasting color',
        '30 days moneyback guarantee',
      ],
      category: ['Fashion', 'Sports'],
      color: { Blue: { id: 1, imgLink: require('./assets/roboarm.jpg') }, Red: { id: 2, imgLink: require('./assets/roboarm.jpg') } },
      size: { L: 1, M: 1, XL: 5 },
      return: 30,
      totalSold: 25,
      rating: 4.5,
      totalRatings: 100,
      discount: 20,
      saleDiscount: 30,
      previousPrice: 50,
      currentPrice: 40,
      condition: 'Used 1 Month',
    },
    // Additional data
    {
      id: 4,
      name: 'Apple iPhone 12',
      description: [
        '6.1-inch Super Retina XDR display',
        'A14 Bionic chip with next-generation Neural Engine',
        'Dual-camera system with 12MP Ultra Wide and Wide cameras',
        'Night mode, Deep Fusion, and Smart HDR 3',
      ],
      category: 'Electronics',
      color: { Black: { id: 3, imgLink: require('./assets/roboarm.jpg') }, White: { id: 4, imgLink: require('./assets/roboarm.jpg') } },
      size: { 64: 5, 128: 3, 256: 2 },
      return: 30,
      totalSold: 50,
      rating: 4.8,
      totalRatings: 500,
      discount: 15,
      saleDiscount: 0,
      previousPrice: 999,
      currentPrice: 849,
      condition: 'New',
    },
    {
      id: 5,
      name: 'Harry Potter and the Sorcerer\'s Stone',
      description: [
        'First book in the Harry Potter series',
        'Written by J.K. Rowling',
        'Follows the journey of Harry Potter, a young wizard',
        'Adventure, magic, and friendship',
      ],
      category: 'Books',
      color: { Blue: { id: 5, imgLink: require('./assets/roboarm.jpg') }, Red: { id: 6, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 5, Paperback: 3, Ebook: 2 },
      return: 30,
      totalSold: 100,
      rating: 4.9,
      totalRatings: 1000,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 15,
      currentPrice: 13.5,
      condition: 'New',
    },
    {
      id: 6,
      name: 'Adidas Ultraboost Shoes',
      description: [
        'Ideal for running and athletic activities',
        'Responsive Boost midsole for comfortable cushioning',
        'Breathable and lightweight Primeknit upper',
        'Durable rubber outsole for traction',
      ],
      category: 'Fashion',
      color: { Black: { id: 7, imgLink: require('./assets/roboarm.jpg') }, White: { id: 8, imgLink: require('./assets/roboarm.jpg') } },
      size: { 7: 3, 8: 5, 9: 2 },
      return: 30,
      totalSold: 75,
      rating: 4.7,
      totalRatings: 800,
      discount: 25,
      saleDiscount: 0,
      previousPrice: 180,
      currentPrice: 135,
      condition: 'New',
    },
    {
      id: 7,
      name: 'Gourmet Chocolate Assortment',
      description: [
        'Delicious assortment of gourmet chocolates',
        'Variety of flavors and fillings',
        'Perfect for gifting or indulging',
      ],
      category: 'Food',
      color: { Brown: { id: 9, imgLink: require('./assets/roboarm.jpg') }, Gold: { id: 10, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 3, Large: 1 },
      return: 30,
      totalSold: 50,
      rating: 4.6,
      totalRatings: 400,
      discount: 0,
      saleDiscount: 0,
      previousPrice: 30,
      currentPrice: 30,
      condition: 'New',
    },
    {
      id: 8,
      name: 'Monalisa Canvas Wall Art',
      description: [
        'Reproduction of the famous painting by Leonardo da Vinci',
        'High-quality canvas print',
        'Stretched and framed',
        'Ready to hang',
      ],
      category: 'Collectibles and Art',
      color: { Multicolor: { id: 11, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 1, Medium: 3, Large: 2 },
      return: 30,
      totalSold: 20,
      rating: 4.8,
      totalRatings: 150,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 80,
      currentPrice: 72,
      condition: 'New',
    },
    {
      id: 9,
      name: 'Nike Dri-FIT Men\'s Training Pants',
      description: [
        'Moisture-wicking fabric keeps you dry and comfortable',
        'Elastic waistband with adjustable drawcord',
        'Side pockets for convenient storage',
        'Tapered fit for a modern look',
      ],
      category: 'Sports',
      color: { Black: { id: 12, imgLink: require('./assets/roboarm.jpg') }, Gray: { id: 13, imgLink: require('./assets/roboarm.jpg') } },
      size: { S: 2, M: 4, L: 3 },
      return: 30,
      totalSold: 30,
      rating: 4.7,
      totalRatings: 250,
      discount: 20,
      saleDiscount: 0,
      previousPrice: 60,
      currentPrice: 48,
      condition: 'New',
    },
    {
      id: 10,
      name: 'Fitbit Charge 4 Fitness Tracker',
      description: [
        'Tracks heart rate, sleep, and activity levels',
        'Built-in GPS for tracking distance and pace',
        'Swimproof design',
        'Up to 7 days of battery life',
      ],
      category: 'Electronics',
      color: { Black: { id: 14, imgLink: require('./assets/roboarm.jpg') }, Rose: { id: 15, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 3, Large: 2, 'One Size': 1 },
      return: 30,
      totalSold: 80,
      rating: 4.6,
      totalRatings: 600,
      discount: 15,
      saleDiscount: 0,
      previousPrice: 150,
      currentPrice: 127.5,
      condition: 'New',
    },
    {
      id: 11,
      name: 'The Great Gatsby',
      description: [
        'Classic novel by F. Scott Fitzgerald',
        'Set in the Roaring Twenties',
        'Explores themes of wealth, love, and the American Dream',
        'Iconic characters and memorable storytelling',
      ],
      category: 'Books',
      color: { Blue: { id: 16, imgLink: require('./assets/roboarm.jpg') }, Gold: { id: 17, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 4, Paperback: 6, Ebook: 2 },
      return: 30,
      totalSold: 150,
      rating: 4.9,
      totalRatings: 1200,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 12,
      currentPrice: 10.8,
      condition: 'New',
    },
    
    {
      id: 14,
      name: 'Mona Lisa Framed Print',
      description: [
        'Art print of the famous Mona Lisa painting',
        'High-quality print on archival paper',
        'Elegant frame included',
        'Ready to hang',
      ],
      category: 'Collectibles and Art',
      color: { Sepia: { id: 22, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 2, Large: 1 },
      return: 30,
      totalSold: 15,
      rating: 4.9,
      totalRatings: 100,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 50,
      currentPrice: 45,
      condition: 'New',
    },
    {
      id: 15,
      name: 'Nike Air Max 270 Sneakers',
      description: [
        'Comfortable and stylish sneakers',
        'Max Air unit for cushioning and support',
        'Breathable mesh upper',
        'Durable rubber outsole',
      ],
      category: 'Fashion',
      color: { Black: { id: 23, imgLink: require('./assets/roboarm.jpg') }, White: { id: 24, imgLink: require('./assets/roboarm.jpg') } },
      size: { 6: 1, 7: 3, 8: 5 },
      return: 30,
      totalSold: 60,
      rating: 4.7,
      totalRatings: 500,
      discount: 25,
      saleDiscount: 0,
      previousPrice: 150,
      currentPrice: 112.5,
      condition: 'New',
    },
    {
      id: 17,
      name: 'Apple AirPods Pro',
      description: [
        'Active noise cancellation for immersive sound',
        'Transparency mode to hear the world around you',
        'Customizable fit for all-day comfort',
        'Sweat and water resistant',
      ],
      category: 'Electronics',
      color: { White: { id: 27, imgLink: require('./assets/roboarm.jpg') } },
      size: { 'One Size': 5 },
      return: 30,
      totalSold: 100,
      rating: 4.9,
      totalRatings: 800,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 249,
      currentPrice: 224.1,
      condition: 'New',
    },
    {
      id: 18,
      name: 'To Kill a Mockingbird',
      description: [
        'Classic novel by Harper Lee',
        'Explores themes of racial injustice and morality',
        'Narrated by Scout Finch, a young girl in the 1930s',
        'Powerful storytelling and memorable characters',
      ],
      category: 'Books',
      color: { Blue: { id: 28, imgLink: require('./assets/roboarm.jpg') }, Black: { id: 29, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 3, Paperback: 4, Ebook: 2 },
      return: 30,
      totalSold: 120,
      rating: 4.9,
      totalRatings: 1000,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 10,
      currentPrice: 9,
      condition: 'New',
    },
    {
      id: 19,
      name: 'Ray-Ban Classic Aviator Sunglasses',
      description: [
        'Iconic aviator style sunglasses',
        'Metal frame with G-15 lenses',
        '100% UV protection',
        'Timeless and versatile',
      ],
      category: 'Fashion',
      color: { Gold: { id: 30, imgLink: require('./assets/roboarm.jpg') }, Silver: { id: 31, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 3, Large: 1 },
      return: 30,
      totalSold: 80,
      rating: 4.8,
      totalRatings: 700,
      discount: 20,
      saleDiscount: 0,
      previousPrice: 150,
      currentPrice: 120,
      condition: 'New',
    },
    {
      id: 20,
      name: 'Assorted Vinyl Records',
      description: [
        'Collection of assorted vinyl records',
        'Various genres and artists',
        'Great for collectors and music lovers',
        'Vintage and nostalgic',
      ],
      category: 'Collectibles and Art',
      color: { Multicolor: { id: 32, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 5, Medium: 3, Large: 2 },
      return: 30,
      totalSold: 50,
      rating: 4.7,
      totalRatings: 400,
      discount: 15,
      saleDiscount: 0,
      previousPrice: 20,
      currentPrice: 17,
      condition: 'Used',
    },
    {
      id: 21,
      name: 'Adidas Originals Stan Smith Sneakers',
      description: [
        'Classic and iconic sneakers',
        'Smooth leather upper',
        'Perforated 3-Stripes design',
        'Rubber cupsole for traction',
      ],
      category: 'Fashion',
      color: { White: { id: 33, imgLink: require('./assets/roboarm.jpg') }, Green: { id: 34, imgLink: require('./assets/roboarm.jpg') } },
      size: { 6: 1, 7: 3, 8: 5 },
      return: 30,
      totalSold: 70,
      rating: 4.6,
      totalRatings: 600,
      discount: 25,
      saleDiscount: 0,
      previousPrice: 80,
      currentPrice: 60,
      condition: 'New',
    },
    {
      id: 23,
      name: 'Original Star Wars Movie Poster',
      description: [
        'Vintage movie poster for the original Star Wars trilogy',
        'High-quality print on archival paper',
        'Iconic artwork and design',
        'Perfect for Star Wars fans and collectors',
      ],
      category: 'Collectibles and Art',
      color: { Multicolor: { id: 36, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 2, Large: 1 },
      return: 30,
      totalSold: 25,
      rating: 4.9,
      totalRatings: 200,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 50,
      currentPrice: 45,
      condition: 'New',
    },
    {
      id: 24,
      name: 'Yoga Mat',
      description: [
        'High-quality yoga mat',
        'Non-slip surface for stability',
        'Cushioned for comfort',
        'Easy to clean and store',
      ],
      category: 'Sports',
      color: { Purple: { id: 37, imgLink: require('./assets/roboarm.jpg') }, Blue: { id: 38, imgLink: require('./assets/roboarm.jpg') } },
      size: { Standard: 5 },
      return: 30,
      totalSold: 55,
      rating: 4.7,
      totalRatings: 500,
      discount: 20,
      saleDiscount: 0,
      previousPrice: 30,
      currentPrice: 24,
      condition: 'New',
    },
    {
      id: 25,
      name: 'Amazon Kindle Paperwhite',
      description: [
        'High-resolution e-reader with built-in light',
        'Anti-glare display for reading in any lighting conditions',
        'Waterproof for worry-free reading by the pool or beach',
        'Long battery life',
      ],
      category: 'Electronics',
      color: { Black: { id: 39, imgLink: require('./assets/roboarm.jpg') } },
      size: { '8GB': 2, '32GB': 1 },
      return: 30,
      totalSold: 90,
      rating: 4.8,
      totalRatings: 800,
      discount: 15,
      saleDiscount: 0,
      previousPrice: 129,
      currentPrice: 109.65,
      condition: 'New',
    },
    {
      id: 26,
      name: 'The Great Gatsby',
      description: [
        'Classic novel by F. Scott Fitzgerald',
        'Set in the 1920s during the Jazz Age',
        'Captivating story of wealth, love, and the American Dream',
        'Timeless literary masterpiece',
      ],
      category: 'Books',
      color: { Blue: { id: 40, imgLink: require('./assets/roboarm.jpg') }, Black: { id: 41, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 3, Paperback: 4, Ebook: 2 },
      return: 30,
      totalSold: 150,
      rating: 4.9,
      totalRatings: 1200,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 12,
      currentPrice: 10.8,
      condition: 'New',
    },
    {
      id: 27,
      name: 'Leather Crossbody Bag',
      description: [
        'Stylish and versatile crossbody bag',
        'Made from genuine leather',
        'Adjustable strap for a comfortable fit',
        'Spacious interior with multiple pockets',
      ],
      category: 'Fashion',
      color: { Brown: { id: 42, imgLink: require('./assets/roboarm.jpg') }, Black: { id: 43, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 2, Large: 1 },
      return: 30,
      totalSold: 70,
      rating: 4.7,
      totalRatings: 600,
      discount: 25,
      saleDiscount: 0,
      previousPrice: 80,
      currentPrice: 60,
      condition: 'New',
    },
    {
      id: 28,
      name: 'Wireless Bluetooth Earbuds',
      description: [
        'True wireless earbuds with Bluetooth connectivity',
        'Compact and lightweight design',
        'Long battery life and quick charging',
        'High-quality sound and noise cancellation',
      ],
      category: 'Electronics',
      color: { Black: { id: 44, imgLink: require('./assets/roboarm.jpg') }, White: { id: 45, imgLink: require('./assets/roboarm.jpg') } },
      size: { 'One Size': 5 },
      return: 30,
      totalSold: 120,
      rating: 4.6,
      totalRatings: 1000,
      discount: 20,
      saleDiscount: 0,
      previousPrice: 50,
      currentPrice: 40,
      condition: 'New',
    },
    {
      id: 29,
      name: 'Vegetarian Cookbook',
      description: [
        'Collection of delicious vegetarian recipes',
        'Includes breakfast, lunch, dinner, and dessert options',
        'Easy-to-follow instructions',
        'Healthy and flavorful meals',
      ],
      category: 'Food',
      color: { Green: { id: 46, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 2, Paperback: 3, Ebook: 1 },
      return: 30,
      totalSold: 90,
      rating: 4.8,
      totalRatings: 800,
      discount: 15,
      saleDiscount: 0,
      previousPrice: 25,
      currentPrice: 21.25,
      condition: 'New',
    },
    {
      id: 30,
      name: 'Vintage Vinyl Record Player',
      description: [
        'Vintage-style record player with built-in speakers',
        'Plays 33 1/3, 45, and 78 RPM records',
        'Classic design with modern technology',
        'Portable and compact',
      ],
      category: 'Collectibles and Art',
      color: { Red: { id: 47, imgLink: require('./assets/roboarm.jpg') }, Blue: { id: 48, imgLink: require('./assets/roboarm.jpg') } },
      size: { Small: 2, Medium: 2, Large: 1 },
      return: 30,
      totalSold: 60,
      rating: 4.7,
      totalRatings: 500,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 100,
      currentPrice: 90,
      condition: 'New',
    },
    {
      id: 31,
      name: 'Resistance Bands Set',
      description: [
        'Set of resistance bands for strength training and fitness',
        'Multiple resistance levels for different exercises',
        'Compact and portable',
        'Suitable for all fitness levels',
      ],
      category: 'Sports',
      color: { Yellow: { id: 49, imgLink: require('./assets/roboarm.jpg') }, Green: { id: 50, imgLink: require('./assets/roboarm.jpg') } },
      size: { 'Set of 3': 4, 'Set of 5': 3, 'Set of 7': 1 },
      return: 30,
      totalSold: 100,
      rating: 4.9,
      totalRatings: 800,
      discount: 20,
      saleDiscount: 0,
      previousPrice: 35,
      currentPrice: 28,
      condition: 'New',
    },
    {
      id: 32,
      name: 'Harry Potter and the Sorcerer\'s Stone',
      description: [
        'First book in the Harry Potter series',
        'Fantasy adventure for all ages',
        'Introduces the magical world of Hogwarts',
        'Beloved characters and captivating storytelling',
      ],
      category: 'Books',
      color: { Blue: { id: 51, imgLink: require('./assets/roboarm.jpg') }, Black: { id: 52, imgLink: require('./assets/roboarm.jpg') } },
      size: { Hardcover: 3, Paperback: 4, Ebook: 2 },
      return: 30,
      totalSold: 200,
      rating: 4.9,
      totalRatings: 1500,
      discount: 10,
      saleDiscount: 0,
      previousPrice: 15,
      currentPrice: 13.5,
      condition: 'New',
    },
    {
      id: 33,
      name: 'Casual Canvas Shoes',
      description: [
        'Comfortable and stylish casual shoes',
        'Durable canvas material',
        'Slip-on design for easy wear',
        'Versatile for everyday use',
      ],
      category: 'Fashion',
      color: { Black: { id: 53, imgLink: require('./assets/roboarm.jpg') }, Gray: { id: 54, imgLink: require('./assets/roboarm.jpg') } },
      size: { 'US 7': 2, 'US 8': 3, 'US 9': 1 },
      return: 30,
      totalSold: 80,
      rating: 4.7,
      totalRatings: 600,
      discount: 25,
      saleDiscount: 0,
      previousPrice: 50,
      currentPrice: 37.5,
      condition: 'New',
    },
    {
      id: 34,
      name: 'Gourmet Coffee Beans',
      description: [
        'Premium gourmet coffee beans',
        'Roasted to perfection',
        'Rich and aromatic flavor',
        'Ideal for coffee lovers',
      ],
      category: 'Food',
      color: { Brown: { id: 55, imgLink: require('./assets/roboarm.jpg') } },
      size: { '250g': 4, '500g': 2, '1kg': 1 },
      return: 30,
      totalSold: 50,
      rating: 4.8,
      totalRatings: 400,
      discount: 0,
      saleDiscount: 0,
      previousPrice: 20,
      currentPrice: 20,
      condition: 'New',
    }
]